apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-secrets.yaml
  - 01-postgres-pvc.yaml
  - 02-postgres-deployment.yaml
  - 03-postgres-service.yaml
  - 04-keycloak-deployment.yaml
  - 05-keycloak-service.yaml
