apiVersion: v1
kind: Service
metadata:
  name: satmonitor-discovery
  labels:
    app.kubernetes.io/name: satmonitor-discovery
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: satmonitor-discovery
  ports:
    - name: http
      port: 8761
      targetPort: http
