apiVersion: v1
kind: Service
metadata:
  name: satmonitor-backend-login
  labels:
    app.kubernetes.io/name: satmonitor-backend-login
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: satmonitor-backend-login
  ports:
    - name: http
      port: 8080
      targetPort: http
