apiVersion: v1
kind: Service
metadata:
  name: satmonitor-frontend
  labels:
    app.kubernetes.io/name: satmonitor-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: satmonitor-frontend
  ports:
    - name: http
      port: 80
      targetPort: http
